import { TeeTime, CourseTier } from "@/types";

export function makeTeeTime(overrides: Partial<TeeTime> = {}): TeeTime {
  return {
    id: "t1",
    courseName: "Test Course",
    courseId: "c1",
    address: "1 Golf Rd",
    city: "Testville",
    state: "CA",
    zipCode: "90000",
    latitude: 37,
    longitude: -122,
    dateTime: "2026-04-18T14:00:00Z",
    displayTime: "2:00 PM",
    displayDate: "Sat, Apr 18",
    players: 2,
    holes: 18,
    originalPrice: 100,
    price: 80,
    isHotDeal: false,
    discount: 20,
    rating: 4.0,
    reviewCount: 50,
    imageUrl: "https://example.com/i.jpg",
    bookingUrl: "https://www.golfnow.com/",
    distanceMiles: 5,
    tier: "standard" as CourseTier,
    ...overrides,
  };
}

export function sampleTeeTimes(): TeeTime[] {
  return [
    makeTeeTime({
      id: "a",
      courseName: "Eagle Ridge",
      price: 65,
      distanceMiles: 2,
      rating: 3.4,
      holes: 18,
      tier: "standard",
      isHotDeal: false,
      displayTime: "8:00 AM",
      dateTime: "2026-04-18T15:00:00Z",
    }),
    makeTeeTime({
      id: "b",
      courseName: "Gavilan",
      price: 18,
      distanceMiles: 0,
      rating: 4.4,
      holes: 9,
      tier: "budget",
      isHotDeal: true,
      displayTime: "6:15 AM",
      dateTime: "2026-04-18T13:15:00Z",
    }),
    makeTeeTime({
      id: "c",
      courseName: "Cinnabar Hills",
      price: 120,
      distanceMiles: 14,
      rating: 4.7,
      holes: 18,
      tier: "premium",
      isHotDeal: false,
      displayTime: "11:30 AM",
      dateTime: "2026-04-18T18:30:00Z",
    }),
    makeTeeTime({
      id: "d",
      courseName: "San Juan Oaks",
      price: 99,
      distanceMiles: 15,
      rating: 4.6,
      holes: 18,
      tier: "premium",
      isHotDeal: true,
      displayTime: "2:45 PM",
      dateTime: "2026-04-18T21:45:00Z",
    }),
    makeTeeTime({
      id: "e",
      courseName: "Twin Creeks",
      price: 30,
      distanceMiles: 22,
      rating: 4.4,
      holes: 9,
      tier: "budget",
      isHotDeal: false,
      displayTime: "4:00 PM",
      dateTime: "2026-04-18T23:00:00Z",
    }),
  ];
}
